version: "3.8"

services:
  db:
    image: ankane/pgvector
    container_name: pgvector-v2-db
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
      POSTGRES_DB: rag_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  fastapi:
    build:
      context: ./rag-fastapi-backend
    container_name: rag-fastapi
    ports:
      - "8001:9001"
    depends_on:
      - db
    volumes:
      - ./uploads:/var/uploads
    environment:
      NEST_API: http://nest:6001
      GEMINI_API_KEY: AIzaSyDEu4OYthxGV-osjSJ_xQW3mx00VKz4T5U
      UPLOAD_DIR: /var/uploads
      DATABASE_URL: postgresql://rag_user:rag_pass@db:5432/rag_db

  nest:
    build:
      context: ./rag-nest-backend
    container_name: rag-nest
    ports:
      - "5001:6001"
    depends_on:
      - db
    volumes:
      - ./uploads:/var/uploads
    environment:
      FAST_API_URL: http://fastapi:9001
      JWT_SECRET: mystrongsecret
      JWT_EXPIRES_IN: 1d
      SERVER_PORT: 6001
      UPLOAD_DIR: /var/uploads
      DATABASE_URL: postgresql://rag_user:rag_pass@db:5432/rag_db

  frontend:
    build:
      context: ./rag-frontend-react-vite
    container_name: rag-frontend
    ports:
      - "4000:80"
    depends_on:
      - fastapi
      - nest

volumes:
  pgdata:
